CREATE TABLE IF NOT EXISTS booking_requests (
  id TEXT PRIMARY KEY NOT NULL,
  status TEXT NOT NULL DEFAULT 'submitted',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  arrival TEXT NOT NULL,
  departure TEXT NOT NULL,
  legal_name TEXT NOT NULL,
  email TEXT NOT NULL,
  mobile_phone TEXT NOT NULL,
  address_line_1 TEXT NOT NULL,
  address_line_2 TEXT,
  city TEXT NOT NULL,
  province TEXT NOT NULL,
  postal_code TEXT NOT NULL,
  country TEXT NOT NULL,
  adults INTEGER NOT NULL,
  children INTEGER NOT NULL DEFAULT 0,
  adult_guest_names_json TEXT NOT NULL,
  stay_reason TEXT NOT NULL,
  vehicle_count INTEGER NOT NULL DEFAULT 0,
  pets_attending INTEGER NOT NULL DEFAULT 0,
  pet_details TEXT,
  additional_notes TEXT,
  minimum_age_confirmed INTEGER NOT NULL DEFAULT 0,
  primary_renter_staying INTEGER NOT NULL DEFAULT 0,
  registered_guests_only_accepted INTEGER NOT NULL DEFAULT 0,
  id_requirement_accepted INTEGER NOT NULL DEFAULT 0,
  agreement_requirement_accepted INTEGER NOT NULL DEFAULT 0,
  payment_requirement_accepted INTEGER NOT NULL DEFAULT 0,
  security_deposit_requirement_accepted INTEGER NOT NULL DEFAULT 0,
  request_only_accepted INTEGER NOT NULL DEFAULT 0,
  booking_conditions_accepted INTEGER NOT NULL DEFAULT 0,
  privacy_notice_accepted INTEGER NOT NULL DEFAULT 0,
  booking_conditions_version TEXT NOT NULL,
  privacy_notice_version TEXT NOT NULL,
  acknowledgements_accepted_at TEXT NOT NULL,
  quote_currency TEXT NOT NULL,
  quote_nights_subtotal_cents INTEGER NOT NULL DEFAULT 0,
  quote_cleaning_fee_cents INTEGER NOT NULL DEFAULT 0,
  quote_tax_rate_basis_points INTEGER NOT NULL DEFAULT 0,
  quote_tax_cents INTEGER NOT NULL DEFAULT 0,
  pricing_version TEXT NOT NULL,
  price_breakdown_json TEXT NOT NULL,
  quoted_at TEXT NOT NULL,
  rental_total_cents INTEGER NOT NULL DEFAULT 0,
  security_deposit_cents INTEGER NOT NULL DEFAULT 0,
  agreement_status TEXT NOT NULL DEFAULT 'not_started',
  agreement_provider TEXT,
  agreement_provider_id TEXT,
  identity_status TEXT NOT NULL DEFAULT 'not_started',
  identity_provider TEXT,
  identity_session_id TEXT,
  rental_payment_status TEXT NOT NULL DEFAULT 'not_requested',
  security_deposit_status TEXT NOT NULL DEFAULT 'not_requested'
);

CREATE INDEX IF NOT EXISTS booking_requests_status_idx ON booking_requests(status);
CREATE INDEX IF NOT EXISTS booking_requests_arrival_departure_idx ON booking_requests(arrival, departure);
