import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const bookingRequests = sqliteTable("booking_requests", {
  id: text("id").primaryKey(),
  status: text("status").notNull().default("submitted"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
  arrival: text("arrival").notNull(),
  departure: text("departure").notNull(),
  legalName: text("legal_name").notNull(),
  email: text("email").notNull(),
  mobilePhone: text("mobile_phone").notNull(),
  addressLine1: text("address_line_1").notNull(),
  addressLine2: text("address_line_2"),
  city: text("city").notNull(),
  province: text("province").notNull(),
  postalCode: text("postal_code").notNull(),
  country: text("country").notNull(),
  adults: integer("adults").notNull(),
  children: integer("children").notNull().default(0),
  adultGuestNamesJson: text("adult_guest_names_json").notNull(),
  stayReason: text("stay_reason").notNull(),
  vehicleCount: integer("vehicle_count").notNull().default(0),
  petsAttending: integer("pets_attending", { mode: "boolean" }).notNull().default(false),
  petDetails: text("pet_details"),
  additionalNotes: text("additional_notes"),
  minimumAgeConfirmed: integer("minimum_age_confirmed", { mode: "boolean" }).notNull().default(false),
  primaryRenterStaying: integer("primary_renter_staying", { mode: "boolean" }).notNull().default(false),
  registeredGuestsOnlyAccepted: integer("registered_guests_only_accepted", { mode: "boolean" }).notNull().default(false),
  idRequirementAccepted: integer("id_requirement_accepted", { mode: "boolean" }).notNull().default(false),
  agreementRequirementAccepted: integer("agreement_requirement_accepted", { mode: "boolean" }).notNull().default(false),
  paymentRequirementAccepted: integer("payment_requirement_accepted", { mode: "boolean" }).notNull().default(false),
  securityDepositRequirementAccepted: integer("security_deposit_requirement_accepted", { mode: "boolean" }).notNull().default(false),
  requestOnlyAccepted: integer("request_only_accepted", { mode: "boolean" }).notNull().default(false),
  bookingConditionsAccepted: integer("booking_conditions_accepted", { mode: "boolean" }).notNull().default(false),
  privacyNoticeAccepted: integer("privacy_notice_accepted", { mode: "boolean" }).notNull().default(false),
  bookingConditionsVersion: text("booking_conditions_version").notNull(),
  privacyNoticeVersion: text("privacy_notice_version").notNull(),
  acknowledgementsAcceptedAt: text("acknowledgements_accepted_at").notNull(),
  quoteCurrency: text("quote_currency").notNull(),
  quoteNightsSubtotalCents: integer("quote_nights_subtotal_cents").notNull().default(0),
  quoteCleaningFeeCents: integer("quote_cleaning_fee_cents").notNull().default(0),
  quoteTaxRateBasisPoints: integer("quote_tax_rate_basis_points").notNull().default(0),
  quoteTaxCents: integer("quote_tax_cents").notNull().default(0),
  pricingVersion: text("pricing_version").notNull(),
  priceBreakdownJson: text("price_breakdown_json").notNull(),
  quotedAt: text("quoted_at").notNull(),
  rentalTotalCents: integer("rental_total_cents").notNull().default(0),
  securityDepositCents: integer("security_deposit_cents").notNull().default(0),
  agreementStatus: text("agreement_status").notNull().default("not_started"),
  agreementProvider: text("agreement_provider"),
  agreementProviderId: text("agreement_provider_id"),
  identityStatus: text("identity_status").notNull().default("not_started"),
  identityProvider: text("identity_provider"),
  identitySessionId: text("identity_session_id"),
  rentalPaymentStatus: text("rental_payment_status").notNull().default("not_requested"),
  securityDepositStatus: text("security_deposit_status").notNull().default("not_requested"),
});
